// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDI_-pnCJx7ibYn1n3jAMXW9jztYxV2qw',
    appId: '1:803509563468:web:4c15a9bf12c7a11f9044e9',
    messagingSenderId: '803509563468',
    projectId: 'exspend-e8333',
    authDomain: 'exspend-e8333.firebaseapp.com',
    storageBucket: 'exspend-e8333.firebasestorage.app',
    measurementId: 'G-K0WP0Q7EGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_cyqua5Y-5hiigr1PkT3vVD7qfUi8pWc',
    appId: '1:803509563468:android:5d7b06901c17ae119044e9',
    messagingSenderId: '803509563468',
    projectId: 'exspend-e8333',
    storageBucket: 'exspend-e8333.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUQ3x52noVb9bnH8uVVo6G49cr5vSswMw',
    appId: '1:803509563468:ios:9bdcd79588d895fe9044e9',
    messagingSenderId: '803509563468',
    projectId: 'exspend-e8333',
    storageBucket: 'exspend-e8333.firebasestorage.app',
    iosBundleId: 'com.example.exSpend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUQ3x52noVb9bnH8uVVo6G49cr5vSswMw',
    appId: '1:803509563468:ios:9bdcd79588d895fe9044e9',
    messagingSenderId: '803509563468',
    projectId: 'exspend-e8333',
    storageBucket: 'exspend-e8333.firebasestorage.app',
    iosBundleId: 'com.example.exSpend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDI_-pnCJx7ibYn1n3jAMXW9jztYxV2qw',
    appId: '1:803509563468:web:83c35d3eaf9b695b9044e9',
    messagingSenderId: '803509563468',
    projectId: 'exspend-e8333',
    authDomain: 'exspend-e8333.firebaseapp.com',
    storageBucket: 'exspend-e8333.firebasestorage.app',
    measurementId: 'G-L2LNSPBT6K',
  );
}
